name: EC2 Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'   # 9 AM IST
    - cron: '30 12 * * *'  # 6 PM IST

jobs:
  ec2-control:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::YOUR_ACCOUNT_ID:role/github-ec2-lambda-role
        aws-region: us-east-1

    - name: Start EC2
      run: |
        aws lambda invoke \
        --function-name ec2-controller \
        --payload '{"action":"start"}' \
        response.json
